#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# meanfield documentation build configuration file, created by
# sphinx-quickstart on Fri Jul  5 12:15:38 2019.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(
    0,
    os.path.abspath(os.path.join("..")),
)
sys.path.insert(
    1,
    os.path.abspath(os.path.join(".")),
)

# -- Project information -----------------------------------------------------
project = "planarfibers"
import datetime

year = datetime.datetime.now().year

copyright = f"{year}, Julian Karl Bauer"
author = "Julian Karl Bauer"


# The full version, including alpha/beta/rc tags.
release = "0.0.2"

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "nbsphinx",
    # 'sphinx.ext.autosummary',
    # 'numpydoc',
]

pygments_style = "sphinx"


source_suffix = ".rst"

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
