name: Build files for publishing to PyPI

on: push

jobs:
  build:

    name: Build distributions 📦 for PyPI
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install setuptools and wheel
      run: >-
        python -m pip install --user --upgrade setuptools wheel

    - name: Build a binary wheel and a source tarball
      run: >-
        python setup.py sdist bdist_wheel
